set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[0].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[1].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[2].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[3].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[4].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[5].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[6].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[7].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[8].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[9].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[10].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[11].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[12].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[13].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[14].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[15].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[16].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[17].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[18].lut6_nand_inst/input1}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[19].lut6_nand_inst/input1}]


set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[0].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X3Y15 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[0].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[0].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X3Y15 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[0].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[1].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[1].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[1].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[1].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[2].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X13Y6 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[2].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[2].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X13Y6 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[2].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[3].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X29Y73 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[3].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[3].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X29Y73 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[3].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[4].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X67Y146 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[4].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[4].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X67Y146 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[4].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[5].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X73Y33 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[5].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[5].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X73Y33 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[5].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[6].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X88Y114 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[6].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[6].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X88Y114 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[6].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[7].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X91Y78 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[7].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[7].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X91Y78 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[7].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[8].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X101Y127 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[8].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[8].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X101Y127 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[8].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[9].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X105Y120 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[9].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[9].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X105Y120 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[9].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[10].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[10].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[10].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[10].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[11].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X67Y146 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[11].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[11].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X67Y146 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[11].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[12].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X73Y33 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[12].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[12].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X73Y33 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[12].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[13].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X89Y137 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[13].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[13].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X89Y137 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[13].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[14].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X95Y84 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[14].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[14].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X95Y84 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[14].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[15].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X103Y107 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[15].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[15].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X103Y107 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[15].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[16].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[16].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[16].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X7Y21 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[16].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[17].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X45Y6 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[17].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[17].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X45Y6 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[17].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[18].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X52Y8 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[18].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[18].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X52Y8 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[18].one2two_inst/LUT6_2_inst}]

set_property BEL A6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[19].lut6_nand_inst/LUT6_inst}]
set_property LOC SLICE_X65Y65 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[19].lut6_nand_inst/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[19].one2two_inst/LUT6_2_inst}]
set_property LOC SLICE_X65Y65 [get_cells {design_1_i/ROs_0/inst/ROs_v1_0_S00_AXI_inst/ring_oscillator[19].one2two_inst/LUT6_2_inst}]
